# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" "usb_storage" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "usb_storage" "sd_mod" "xhci_pci" "uas" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/daeb5f1b-72e5-404f-b616-1be34ad0d447";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6C5A-830D";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # Hard wired drives from the NAS combined in a single logical volume
  fileSystems."/mnt/media" = {
    device = "/dev/media_vg/media_lv";
    fsType = "ext4";
  };

  # Nas Media. Deprecated now, unless I get it working again
  fileSystems."/mnt/nas/media" = {
    device = "10.0.0.13:/volume1/media";
    fsType = "nfs";
    options = [ "vers=4" "nofail" "_netdev" "x-systemd.automount" "x-systemd.idle-timeout=600" ];
  };

  boot.initrd.luks.devices = {
    cryptBay2 = {
      device = "/dev/disk/by-uuid/e01c8061-509c-4d5c-ba8d-10199eda50df";
    };
    cryptBay3 = {
      device = "/dev/disk/by-uuid/fbe688c8-4eb8-4068-be9a-539352752a76";
    };
    cryptBay4 = {
      device = "/dev/disk/by-uuid/d34d1433-0bc8-49f7-befa-9648585caeb8";
    };
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
