apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: Kustomize
resources:
  - ./config/metallb.kustomization.yaml
  - ./config/jellyfin.kustomization.yaml
