keys:
  - &yubikey E6028682743BF174D2E5B3AF92810374E3AC1EE1
  - &zenbook age16dtszcmd8thqphvm2tr4vutq2va65qkhap7pt7d3402gknkr4dfswhgemd
  - &lenovo age1y0ts220sv87lxv540wh889zpc2lvanhp8cdpw25dauts59p6gy2q2ky666
  - &pi age1pffk3zqh8kpl2gn0aarw7zqv5q2dh9zvgd5jrj5natxnvyukkdeq0qtgw3
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        - *yubikey # This is used to edit file on other hosts
        age:
        - *zenbook
        - *lenovo
        - *pi
