adminPassword: ENC[AES256_GCM,data:7fPDaVb0xlW+eRD44hWz+QutX764MkuelvgxCQalyHbf7Txr9g==,iv:6q55N9z1k+uV9Xfmq99UKyaHi27Eq4GubFsM33QVOPg=,tag:g1QpdLWHkKrcf2BT8+sPTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-27T00:49:43Z"
    mac: ENC[AES256_GCM,data:JKy73vNUtEg4ywqo8rMUH812qLK6tw2D2taAJ1lKvr6WK0EGfBA1B+NLQJoVH1l1Gv2SxSB+wj+K+Vac5QE9ipgeW/+aDFFVf/rp2CZErNYHBAnYiToa7mDLdA9su+38VAoRPidCnYQDU3alHOUrR7AVDbWisB+IE3ILrWCGFMM=,iv:Y2JJXRGVl4kT07lwgSgsTEWV9r9VJWwdN8Yrb6jIVwA=,tag:huIOPG0n1JOxHFgEhNhRLA==,type:str]
    pgp:
        - created_at: "2025-02-27T00:47:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/9GaQrE9fNtnov80T8uknvTmIFqxnRyLLkT5nQFfsNIuBj
            F2b4yONnyzLDZwsg6ymFVPH8Qt05T/FOvWBrB7op8KIOD9m7xvHFBwvSmpjgQRJB
            uDp13DYgsiWiumPFKt+8Wx+bqriS3/U63IQJIm2albdiCbIMq40J7n4y41bKnhRB
            RtmtUQr9Ij0P1wKUCK+M80B+Y51JGyDsgM9z14+yShwlZarscZbF8DOIP2Bvga6g
            u8p3HCP/JVs7SiBdO89yGokD/e+qL+ljp3Xl+r9HZbt9lQfZKKxV1IGZieQJQuNM
            eAPiiI/IZQFD27jADJ6n/1cz6hTldurZvkLx7gzEEnB/LyhR27NroWk+rDeMDAJL
            8Se+rpnIaxfnE89KFTT4tcRpDw3XNs1ghWO0RfC7IU9XbWTlaiORs4Jgs4vBDtT4
            KNe/Lr6hpA1gy4JopVYl4+nvrDKDVdUEYXVHFv5Ftl1F3oM9kPrtN0DnYFx1Qvo6
            V0c4qZ/lLncvHAoCggc1tK5Oy6Oqou7SRkwG30h8dpUsU/2Fuz3zhJVWc4iHTldU
            G3W82zE6mj4A5tH1LhVksqMuzhadx7uPh7GyzraweqgLu9z1kuADTZ1HJi6ro27/
            kxfA90aoNzPaOpu2sZrvN5kqrHl0UAts/Fyy0+hh1aNDPM6Dr0fcj8rRL3OZzW7S
            XgE4cPWah4GGemUqQTuf4+5XW0zZVr/impwh3khxh5U51szVUDVPfd0HKsd4jMAR
            BfFDCdFamVeaYayGHXPO3/FT8ojTAFIWkpBuxsd3ew9lfW5HDGTI3fSlmBU4JBM=
            =F3sF
            -----END PGP MESSAGE-----
          fp: E6028682743BF174D2E5B3AF92810374E3AC1EE1
    unencrypted_suffix: _unencrypted
    version: 3.9.4
