#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT=$SCRIPT_DIR/..
HOMELAB_LENOVO_ADDRESS=lenovo.home

cd "$ROOT/nixos"
nix flake lock
cd "$ROOT"

sudo nix run github:nix-community/nixos-anywhere \
--extra-experimental-features "nix-command flakes" \
-- --flake "$ROOT/nixos#homelab_lenovo" nixos@$HOMELAB_LENOVO_ADDRESS

ssh-keygen -R $HOMELAB_LENOVO_ADDRESS
