provider: cloudflare
policy: upsert-only
txtOwnerId: "cloudflare-homelab"
domainFilters:
  - "bliztle.com"
serviceAccount:
  create: true
  name: "external-dns-cloudflare"
ingressClassFilters:
  - ingress-nginx
