extraEnvVars:
    - name: ENC[AES256_GCM,data:i6dsV6FnIDKPPJ+lOyqLUgLlDvgt9spuwP+/jw==,iv:J7175p+WIPF1Bsyk4gfhQnnZiHN+4UbAEFRdhF67lms=,tag:cn6+3PVPd+f+Ca54UENaHA==,type:str]
      value: ENC[AES256_GCM,data:CYd+Fpv1cB1CLlsif0wFAW1p69tCD5YQ+YcP1cDfrggXejy+Tw==,iv:zJHNenvOMSZ3iPsnIWEgsZR2ehDqOgYyegArz6xoitc=,tag:YaIs9kn/AeT9U0b4l6ksBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-27T01:31:13Z"
    mac: ENC[AES256_GCM,data:kSLc8/YShbSmdpwvI5S4rlBsnttQlUzT+xebMXjzKQocp+oRf1CpeKVTU0tAIcfggnaPg2FiinwUB0KSxZD7fFr9Agt3mNrCXxNMo1fwXnQkoemxgy/w6i5WmV0EpN881k5q/ggAWjTZMxV9slTjm6jsR3IegehjS+8vgNZ2ZT0=,iv:HNyDeFTceu0RKRoAkMkBd9Pc5rBAC6sBaaaalJnvEtk=,tag:i69pn72OgpVXKELsdahVgw==,type:str]
    pgp:
        - created_at: "2025-02-27T01:21:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/+KmMc9MAUSsLdX8F8N8OCyK4rMiYj/Xyjmy3/sWZKkLWv
            guf+gmNdQKL1sgxCMk3iS8nhLTmAS/0E8JnpwSTI2mK239Ium2LW6oI3adURFZul
            AyhQi6bNGiHF5MZkFy1i02E1u4K7yUCRbffRT7PPygg8LhYCqu4wvgN5laBbaMth
            W5296IC2+S6YUbCSZvwoa4nFOY6db2CYFdKu3H2lXVLCYKJWSOi9AOCWvRcXLmhZ
            dgUnEHE07Og3R7P022Gcd3Zztly6nCVMbg89O/3G7XFBvtPyF0KWqXkis3XYqkSY
            /g2NsitolTxmzyp+kpsC0GoMqvqJBWJOmHWe06mp6KHTzPP0QB5WUPUpicodXqm6
            oL/yJawQYnvUWiWhH1Kpu5uX714pYUnBMYomPtYOauiAI1jdVVb/3HIPAguxpdkY
            YLJeOx/BMGG577N2kVxUnBIvf8gtMLQXF31YNOhr5uPbcnJT7nq04pP30LVMC1Cx
            kLpQKNeEboziV5IO/7Y0d2qQn2Qa04YoIpmJXYCZeiY9wIlyQ4hhVdig4DFyz5Ye
            JqbyYvKQFLiUUr9bmS98vxfMQ6bhK+4x08ZJw2PM7GHU+LyGp8qHhRPygyXCiRNX
            UmbN7LNJyh0E1+8teOfhw7xpdYKoLMWzW96eRlDUY9khMWHgFiVejI+oRjzB4fvS
            XgEyfsGnv69ZK+4gdzPp6TS1fBjbtaEeaFvV0HLIgP/NHg4O7CuIl37nWIIoMEZv
            2LyfsTa2Cl7VJ+2eFwdOhhKkL6CYT//TMf3zO3/TbA5PHVAL8IGX1lXJ4IpJe2c=
            =hNZC
            -----END PGP MESSAGE-----
          fp: E6028682743BF174D2E5B3AF92810374E3AC1EE1
    unencrypted_suffix: _unencrypted
    version: 3.9.4
