---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool # Designates which addresses it is allowed to assign
metadata:
  name: pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.0.192/26
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pool
  namespace: metallb-system
spec:
  ipAddressPools:
    - pool
